name: CI

on: issues

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Substrate Interface 
        run: pip3 install substrate-interface

      - name: Run a one-line script
        run: python3 verify.py "${{ github.event.issue.body }}" 
      
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "Verified Author"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: Unconfirmed

  star_1:
    if: github.event.label.name == 'Normal' && github.event.label.name == 'Aug19-Oct2' 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Substrate Interface 
        run: pip3 install substrate-interface

      - name: Run a one-line script
        run: python3 script.py "${{ github.event.issue.body }}" 1
      
      - name: Commit and push changes
        run: |
          git config --global user.name "felixfaisal"
          git config --global user.email "faisalahmedfarooq46@gmail.com"

          git add -A
          git commit -m "add: ${{ github.event.issue.title }}"
          git push

      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:
  
  star_2:
    if: github.event.label.name == 'Moderate' && github.event.label.name == 'Aug19-Oct2' 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Substrate Interface 
        run: pip3 install substrate-interface

      - name: Run a one-line script
        run: python3 script.py "${{ github.event.issue.body }}" 2
      
      - name: Commit and push changes
        run: |
          git config --global user.name "felixfaisal"
          git config --global user.email "faisalahmedfarooq46@gmail.com"

          git add -A
          git commit -m "add: ${{ github.event.issue.title }}"
          git push

      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:
  star_3:
    if: github.event.label.name == 'Critical' && github.event.label.name == 'Aug19-Oct2' 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Substrate Interface 
        run: pip3 install substrate-interface

      - name: Run a one-line script
        run: python3 script.py "${{ github.event.issue.body }}" 3
      
      - name: Commit and push changes
        run: |
          git config --global user.name "felixfaisal"
          git config --global user.email "faisalahmedfarooq46@gmail.com"

          git add -A
          git commit -m "add: ${{ github.event.issue.title }}"
          git push

      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "Unconfirmed"
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
  
  label_issues_new_cycle:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "Aug19-Oct2"
          repo-token: ${{ secrets.GITHUB_TOKEN }}   
