name: Add labels to new issues

on: 
  issues:
    types: 
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Substrate Interface 
        run: pip3 install substrate-interface

      - name: Run a one-line script
        run: python3 verify.py "${{ github.event.issue.body }}" 
      
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "Verified Author"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: Unconfirmed

  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "Unconfirmed"
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
  
  label_issues_new_cycle:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "Jan1-Feb14"
          repo-token: ${{ secrets.GITHUB_TOKEN }}   
