name: Add labels to new issues

on: 
  issues:
    types: 
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Substrate Interface 
        run: pip3 install substrate-interface

      - name: Run a one-line script
        run: python3 verify.py "${{ github.event.issue.body }}" 
      
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "Verified Author"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: Unconfirmed

  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "Unconfirmed"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  resolve-label:
    name: Resolve label for current cycle
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Resolve label
        id: label
        run: |
          RESOLVED_LABEL=$(./support/scripts/cycle-calculator.sh)
          echo "$RESOLVED_LABEL"
          echo "cycle-label=${RESOLVED_LABEL}" >> "$GITHUB_OUTPUT"
    outputs:
      cycle-label: ${{ steps.label.outputs.cycle-label }}

  label_issues_new_cycle:
    needs: resolve-label
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: ${{ needs.resolve-label.outputs.cycle-label }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
